-- The map point again, this time actually applied.
--
-- 0012 filled `latitude`/`longitude` only `WHERE latitude IS NULL`, on the
-- premise that they had never been set and that a village which had already
-- moved its own pin must keep it. The first half of that premise was wrong: the
-- live site answered with a rendered map whose marker was some other point, so
-- the columns were not null, the guard held, and nothing changed.
--
-- The village supplied -6.2419, 107.1523 for the office, so that is the point
-- that belongs here. This one is unconditional. A migration runs once and is
-- then recorded as applied, so this corrects the stored point without becoming
-- a deploy that re-stamps it every time - a village that moves its pin in
-- Pengaturan Desa afterwards keeps what it chose.
--
-- For a village reselling this script: do not edit this file. The point for a
-- new install comes from db/seed/seed.sql, and after that it is an ordinary
-- field in Pengaturan Desa.

UPDATE villages
   SET latitude = -6.2419,
       longitude = 107.1523
 WHERE id = 'vil_demo';

-- 15 frames the office and the streets around it; 14 shows roughly twice the
-- area, which reads as "somewhere near here" rather than "this building". Left
-- conditional on purpose - zoom is a matter of taste, and unlike a wrong pin a
-- wider view sends nobody to the wrong address.
UPDATE villages
   SET map_zoom = 15
 WHERE id = 'vil_demo' AND map_zoom = 14;
