/// <reference types="@cloudflare/workers-types" />

/**
 * Bindings declared in wrangler.jsonc.
 *
 * `@opennextjs/cloudflare` reads this interface through `getCloudflareContext`.
 * It is committed (rather than generated by `wrangler types`) so that typecheck
 * runs in CI without needing Cloudflare credentials.
 */
declare global {
  interface CloudflareEnv {
    DB: D1Database;
    KV: KVNamespace;
    MEDIA: R2Bucket;
    ASSETS: Fetcher;

    /** Village slug used when the request hostname maps to no tenant. */
    DEFAULT_VILLAGE_SLUG: string;
    APP_NAME: string;

    /**
     * Optional secrets, set with `wrangler secret put`. Absent in local dev.
     */
    SESSION_SECRET?: string;
    TURNSTILE_SECRET_KEY?: string;
  }
}

export {};
