#!/usr/bin/env node
/**
 * Generates the SQL that creates an administrator account.
 *
 * The password is hashed here and only the hash is printed, so no plaintext
 * credential is ever written to a file in the repository or passed through the
 * D1 HTTP API in the clear.
 *
 * Usage:
 *   ADMIN_PASSWORD='...' node scripts/create-admin.mjs \
 *     --email admin@desa.example --name "Nama Admin" --village vil_demo \
 *     > /tmp/create-admin.sql
 *   npx wrangler d1 execute app-desa-db --remote --file=/tmp/create-admin.sql
 *
 * Then delete the generated file.
 */
import { webcrypto as crypto } from "node:crypto";

const PBKDF2_ITERATIONS = 12_000; // must match src/lib/auth.ts

function arg(name, fallback) {
  const index = process.argv.indexOf(`--${name}`);
  if (index !== -1 && process.argv[index + 1]) return process.argv[index + 1];
  return fallback;
}

const email = String(arg("email", "")).trim().toLowerCase();
const fullName = String(arg("name", "Administrator")).trim();
const villageId = String(arg("village", "vil_demo")).trim();
const roleSlug = String(arg("role", "admin")).trim();
const password = process.env.ADMIN_PASSWORD ?? "";

const problems = [];
if (!email || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
  problems.push("--email must be a valid address");
}
if (password.length < 12) {
  problems.push("ADMIN_PASSWORD must be at least 12 characters");
}
if (!["super_admin", "admin", "kepala_desa", "sekretaris_desa", "operator"].includes(roleSlug)) {
  problems.push("--role must be one of: super_admin, admin, kepala_desa, sekretaris_desa, operator");
}
if (problems.length > 0) {
  console.error(`Cannot generate admin SQL:\n - ${problems.join("\n - ")}`);
  process.exit(1);
}

const toHex = (buffer) =>
  [...new Uint8Array(buffer)].map((b) => b.toString(16).padStart(2, "0")).join("");

const salt = crypto.getRandomValues(new Uint8Array(16));
const saltHex = toHex(salt.buffer);

const key = await crypto.subtle.importKey(
  "raw",
  new TextEncoder().encode(password),
  "PBKDF2",
  false,
  ["deriveBits"],
);

const bits = await crypto.subtle.deriveBits(
  { name: "PBKDF2", salt, iterations: PBKDF2_ITERATIONS, hash: "SHA-256" },
  key,
  256,
);

const hash = toHex(bits);
const userId = `usr_${crypto.randomUUID().replace(/-/g, "")}`;
const sql = (value) => `'${String(value).replace(/'/g, "''")}'`;

process.stdout.write(`-- Generated by scripts/create-admin.mjs. Contains a password hash: do not commit.
INSERT INTO users (id, village_id, email, full_name, password_hash, password_salt,
                   status, email_verified)
VALUES (${sql(userId)}, ${sql(villageId)}, ${sql(email)}, ${sql(fullName)},
        ${sql(hash)}, ${sql(saltHex)}, 'active', 1)
ON CONFLICT (village_id, email) DO UPDATE SET
  password_hash = excluded.password_hash,
  password_salt = excluded.password_salt,
  full_name = excluded.full_name,
  status = 'active',
  updated_at = datetime('now');

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.village_id = ${sql(villageId)} AND u.email = ${sql(email)}
  AND r.slug = ${sql(roleSlug)}
ON CONFLICT DO NOTHING;
`);
